apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.metadataName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.labelName}}
  template:
    metadata:
      labels:
        app: {{.Values.labelName}}
    spec:
      containers:
      - name: {{.Values.containerName}}
        image: {{.Values.imageName}}
        ports:
        - containerPort: {{.Values.service.port}}
